In [1]:
import numpy as np

In [2]:
a  = np.array([1, 2, 3, 4, 5, 6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[10] # intentional seg fault

IndexError: index 10 is out of bounds for axis 0 with size 6

In [5]:
a[0]

1

In [17]:
b = np.concatenate((a, a))
b

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [22]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
z = np.array([[7, 8], [9, 10]])

In [33]:
q = np.concatenate((x,z), axis=1)
q

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [34]:
np.concatenate((q[0], q[1]), axis=0)

array([ 1,  2,  7,  8,  3,  4,  9, 10])

In [36]:
x.ndim

2

In [37]:
y.ndim

2

In [38]:
b.ndim

1

In [39]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [40]:
array_example.ndim

3

In [41]:
array_example.size

24

In [42]:
array_example.shape

(3, 2, 4)

In [43]:
array_example.reshape(2, 3, 4)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 2, 3]],

       [[4, 5, 6, 7],
        [0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [44]:
array_example.reshape(3, 2, 4)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [45]:
array_example.reshape(4, 3, 2)

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[6, 7],
        [0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7],
        [0, 1]],

       [[2, 3],
        [4, 5],
        [6, 7]]])

In [47]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [52]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]
